sudo: required

services:
  - docker

language: minimal

env:
  global:
    - secure: "NZnaA9tsHnxUTQSEzuflYT+E2JYM73L4rUk4xsx7gluEVm58sp7qAoAYe2WEJiXxsJY/V/fNSExED90Nx4I/sYj51I6gtvkROO71dM2FVVa/10zh99TfikYLmCV8/KB7NZ+MB4vQXOm5rypYU9anRGoczy+cJiX1hFSIphZXzk7WyKsg6oMBv/CysmDArVhnM+WMUDjCGMKHhAIjWxamqC4fZ834edwDySZDec9CGg7gPvCxAIBz7HTYa1AwJedqAoMSymxEtIg/JA6NVM8VTXhAPESh8amWJV9kOk9phH3V/SW4CMkfk2g30KKC99src/Tjx5Z+vbigWsQC3yUz+GjCyM8XEGXV7FPYyvAmPHOt6TFPDH/EQ5FKMbD5xwsPQYZjUOyAOnkoR8v0PJbv2oi3dfDc3J2MPJvG7hZV0Ex/+DiEf4VEInY7cfTlVAmdF52yJ5KHpEjfKEWkdQQxbLc2qrUPIX5aVl5dxdt0kYyadvz+J/13DtwGIaFDggwbfR7RC1x6AL/PnjqOuRnqPo90Km8MmwNkmkw6PEHJfF5lcOjWGZPIfs/t5zh6AIhvJSW9B8loPGOI+cZ3idhI/WREDdVN3Zkmh2oqoNunN32Y+z3kT6YfrjiT+RUGJhzO24ujZApnrJvU/hFOpGiHNhFr1rY+mZUpk1UD4ItFBl4="
    - secure: "csP7Mq75TGW2V4M66VtLuLmgDl5qYuIqamvistAXD4D15c8IJPT2yqj+HsgP04pmOrFKPe0gw84K5x72aVuibzzFL6JOJKdpwWqcxBWU9JD7xHmUIIj/vk/tBvF8AyVVNWQXvSX11z3v33UjN69w3nq/M6cbFURliAALA75XUuhTgjq4972sOKDdcAzy2BLJc61kST15TMWl4znYSdZ14o+6NDAuSCPeqCIng1nbwKlnhy01Jg29ayqWuod3SqD2QiCZfD3dMZMi7uKz2+f/WwhxareuqZQtZLCCNpQMtdSJmJYbtGhHXe414JD1FjI/jT/QtV23QQttUDYSdp1uga5xPgFMEzFdEvSzj1p1rhcpdRjEqnZOK7NqXjq5k2jRj1uq5R/H+RbK1ft0FO2+nei/fx3z4Xlw6jLgFcMVEDEB/w83Y8KQcbS5izDsSC5zt3+AF4Y8RUJhJk2TANrVC4SGzB+pQqnxEP5Xtn1Z9RGnAKZSVpgMvi/cOF/rSPlLeUEoy0agJ2ojG8y9hNe3bjCN4RhdgqC7T0tuDLy1mPqhPzfMsjZMovwnE5QgekTLa6as7uIbHcdD9m1ERTlwr5VgsSV6lpIu/3mzQeECm00lrH1LToqnDSrlUIzb08RkTvPevP7Sqgj8G5gXLfm1siLOSyUpLTQNnY72q0tb45Q="
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=21void/miningcore-ubuntu

install:
  - docker build -f Dockerfile -t $REPO:$COMMIT .

after_success:
  - docker tag $REPO:$COMMIT $REPO:travis-latest
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO

